const patients = [
  {
    firstName: "Alex",
    middleName: "Thomas",
    lastName: "Johnson",
    username: "alexj",
    email: "alex.johnson@example.com",
    password: "password123",
  },
  {
    firstName: "Maria",
    middleName: "Isabel",
    lastName: "Rodriguez",
    username: "mariar",
    email: "maria.rodriguez@example.com",
    password: "password123",
  },
  {
    firstName: "David",
    middleName: "Edward",
    lastName: "Smith",
    username: "davids",
    email: "david.smith@example.com",
    password: "password123",
  },
  {
    firstName: "Sophia",
    middleName: "Grace",
    lastName: "Brown",
    username: "sophiab",
    email: "sophia.brown@example.com",
    password: "password123",
  },
  {
    firstName: "Michael",
    middleName: "Andrew",
    lastName: "Garcia",
    username: "michaelg",
    email: "michael.garcia@example.com",
    password: "password123",
  },
  {
    firstName: "Emily",
    middleName: "Rose",
    lastName: "Martinez",
    username: "emilym",
    email: "emily.martinez@example.com",
    password: "password123",
  },
  {
    firstName: "Daniel",
    middleName: "James",
    lastName: "Hernandez",
    username: "danielh",
    email: "daniel.hernandez@example.com",
    password: "password123",
  },
  {
    firstName: "Emma",
    middleName: "Louise",
    lastName: "Lee",
    username: "emmal",
    email: "emma.lee@example.com",
    password: "password123",
  },
  {
    firstName: "James",
    middleName: "Robert",
    lastName: "Wilson",
    username: "jamesw",
    email: "james.wilson@example.com",
    password: "password123",
  },
  {
    firstName: "Chloe",
    middleName: "Marie",
    lastName: "Kim",
    username: "chloek",
    email: "chloe.kim@example.com",
    password: "password123",
  },
  {
    firstName: "Ethan",
    middleName: "William",
    lastName: "Nguyen",
    username: "ethann",
    email: "ethan.nguyen@example.com",
    password: "password123",
  },
  {
    firstName: "Ava",
    middleName: "Elizabeth",
    lastName: "Clark",
    username: "avaclark",
    email: "ava.clark@example.com",
    password: "password123",
  },
  {
    firstName: "William",
    middleName: "Joseph",
    lastName: "Jones",
    username: "williamj",
    email: "william.jones@example.com",
    password: "password123",
  },
  {
    firstName: "Mia",
    middleName: "Sophia",
    lastName: "Davis",
    username: "miad",
    email: "mia.davis@example.com",
    password: "password123",
  },
  {
    firstName: "Oliver",
    middleName: "George",
    lastName: "Lopez",
    username: "oliverl",
    email: "oliver.lopez@example.com",
    password: "password123",
  },
];
module.exports = {
  patients,
};
